[build]
  base = "landing-react"
  command = "npm run build"
  publish = "landing-react/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
